version: "3.8"

volumes:
  service_postgres_data:
  pip_cache:

services:
  library-back:
    container_name: library-back
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code
    command: ["./start_library_back.sh"]
    networks:
      - library-network
    ports:
      - "8000:8000"
    volumes:
      - ./library_back:/library_back
      - pip_cache:/usr/local/lib/python3/site-packages
    env_file:
      - ./library_back/env-vars/.postgres.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - service_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./library_back/env-vars/.postgres.env
    networks:
      - library-network

networks:
  # Bridge used to `library-back` comunicate to `db` postgres
  library-network:
    name: library-network
    driver: bridge
