version: "3.8"

volumes:
  service_postgres_data:
  pip_cache:

services:
  db:
    container_name: db
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - service_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./library_back/env-vars/.postgres.env
    networks:
      - library-network

  library-back:
    container_name: library-back
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile_back
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code
      - PORT=8000
    networks:
      - library-network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./library_back:/library_back
      - pip_cache:/usr/local/lib/python3/site-packages
    env_file:
      - ./library_back/env-vars/.postgres.env
    depends_on:
      - db

  library-front:
    container_name: library-front
    restart: on-failure
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile_front
    networks:
      - library-network
    ports:
      - "3000:3000"
    volumes:
      - ./library_front:/library_front
    depends_on:
      - db
      - library-back

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./library_front/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - library-network
    depends_on:
      - library-front

networks:
  # Bridge used to `library-back` comunicate to `db` postgres
  library-network:
    name: library-network
    driver: bridge
